Add Edit in Datawrapper link to footer
datawrapper/chart-core pull request #115
Opened 2021-05-05 12:34 UTC by gka

This PR adds a new block to our visualization footer that lets viewers of a visualization create and edit a copy of it. This only forks for charts which are forkable and have the `metadata.publish.edit-in-datawrapper` attribute set to `true`.

- [ ] add "Edit in Datawrapper" link block and hook it up to our `/create/` endpoint
- [ ] translate caption (en and de for now)
- [ ] allow overwriting of caption through theme

![grafik](https://user-images.githubusercontent.com/617518/117141375-f9f53700-ad9d-11eb-94ac-c874053d5107.png)

2021-05-05 12:49 UTC, elanals commented
Should this maybe go into `publish.blocks` with the (incoming) rest?

2021-05-10 16:47 UTC, davidkokkelink requested changes
looks good but i agree the setting should live in `metadata.publish.blocks` for consistency

2021-05-10 17:51 UTC, gka commented
fine with me :+1:

2021-05-11 09:26 UTC, gka commented
grrr, I'm getting this error during the ci tests now:
![grafik](https://user-images.githubusercontent.com/617518/117792549-e84ade00-b23a-11eb-8f10-3487f18b1b6d.png)

any idea what's causing this?

2021-05-11 09:41 UTC, gka commented
I re-ran the test without changes and it mysteriously ran through this time

2021-05-11 09:51 UTC, ilokhov commented
> I re-ran the test without changes and it mysteriously ran through this time

This also frequently happens in the controls repo, looks like the error is similar as well.

Sometimes this error appears and sometimes it doesn't.

<img width="615" alt="Screenshot 2021-05-11 at 11 50 17" src="https://user-images.githubusercontent.com/6787862/117796149-16d2b400-b24f-11eb-884b-ff25adf3b8f9.png">

2021-05-11 15:40 UTC, davidkokkelink approved these changes

2021-05-12 09:04 UTC, merged